packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@types/bun": ^1.3.4
  "@trpc/server": ^11.7.2
  "@trpc/client": ^11.7.2
  "@trpc/react-query": ^11.7.2
  better-auth: ^1.4.9
  "@libsql/client": 0.15.15
  libsql: 0.5.22
